#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

# Make output directories
mkdir -p out_dir
mkdir -p out_figs

singularity exec docker://brainlife/mne:0.23dev python3 main.py


cat << EOF > product.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "Raw data",
         "base64": "$(base64 -w 0 out_figs/raw.png)"
       },
       {
          "type": "image/png",
	        "name": "Raw cleaned data",
          "base64": "$(base64 -w 0 out_figs/raw_cleaned.png)"
       }
]
}
EOF